import image1 from "../assets/clothes/image1.png";
import image2 from "../assets/clothes/image2.png";
import image3 from "../assets/clothes/image3.png";
import image4 from "../assets/clothes/image4.png";
import image5 from "../assets/clothes/image5.png";
import image6 from "../assets/clothes/image6.png";
import image7 from "../assets/clothes/image7.png";
import image8 from "../assets/clothes/image8.png";
import image9 from "../assets/clothes/image9.png";
import image10 from "../assets/clothes/image10.png";
import image11 from "../assets/clothes/image11.png";
import image12 from "../assets/clothes/image12.png";
import image13 from "../assets/clothes/image13.png";
import image14 from "../assets/clothes/image14.png";
import image15 from "../assets/clothes/image15.png";
import { Product } from "../commons/interfaces";

export const products: Product[] = [
  {
    id: 16,
    name: "CUTWORK POPLIN DRESS",
    price: 9950.0,
    image: image1,
    sizes: ["XS", "S", "M", "L"],
    colors: ["#F3E5D7", "#000000"],
    rating: 4,
    reviews: 87,
  },
  {
    id: 17,
    name: "CUTWORK POPLIN DRESS",
    price: 9950.0,
    image: image2,
    sizes: ["XS", "S", "M", "L"],
    colors: ["#FFB6C1", "#0000FF"],
    rating: 4,
    reviews: 87,
  },
  {
    id: 18,
    name: "CUTWORK POPLIN DRESS",
    price: 9950.0,
    sizes: ["XS", "S", "M", "L"],
    image: image3,
    colors: ["#000000", "#808080"],
    rating: 4,
    reviews: 87,
  },
  {
    id: 19,
    name: "CUTWORK POPLIN DRESS",
    price: 9950.0,
    sizes: ["XS", "S", "M", "L"],
    image: image4,
    colors: ["#D2B48C", "#000000"],
    rating: 4,
    reviews: 87,
  },
];

export const allProducts: Product[] = [
  {
    id: 1,
    name: "TENCIL BLEND POLO",
    price: 9500.0,
    image: image5,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["#1a365d", "#000000", "#e2e8f0", "#3b82f6"],
    rating: 5,
    reviews: 120,
  },
  {
    id: 5,
    name: "CUTWORK POPLIN DRESS",
    price: 9950.0,
    image:image6,
    sizes: ["XS", "S", "M", "L"],
    colors: ["#A0522D", "#000000"],
    rating: 4,
    reviews: 85,
  },
  {
    id: 6,
    name: "CUTWORK POPLIN DRESS",
    price: 9950.0,
    image: image7,
    sizes: ["XS", "S", "M", "L"],
    colors: ["#8B4513", "#000000"],
    rating: 5,
    reviews: 92,
  },
  {
    id: 7,
    name: "CUTWORK POPLIN DRESS",
    price: 9950.0,
    image: image8,
    sizes: ["XS", "S", "M", "L"],
    colors: ["#4682B4", "#000000"],
    rating: 4,
    reviews: 78,
  },
  {
    id: 8,
    name: "CUTWORK POPLIN DRESS",
    price: 9950.0,
    image: image9,
    sizes: ["XS", "S", "M", "L"],
    colors: ["#D2691E", "#000000"],
    rating: 5,
    reviews: 105,
  },
  {
    id: 9,
    name: "CUTWORK POPLIN DRESS",
    price: 9950.0,
    image: image10,
    sizes: ["XS", "S", "M", "L"],
    colors: ["#708090", "#000000"],
    rating: 4,
    reviews: 67,
  },
  {
    id: 10,
    name: "CUTWORK POPLIN DRESS",
    price: 9950.0,
    image: image11,
    sizes: ["XS", "S", "M", "L"],
    colors: ["#8B0000", "#000000"],
    rating: 5,
    reviews: 88,
  },
  {
    id: 11,
    name: "CUTWORK POPLIN DRESS",
    price: 9950.0,
    image: image12,
    sizes: ["XS", "S", "M", "L"],
    colors: ["#556B2F", "#000000"],
    rating: 4,
    reviews: 72,
  },
  {
    id: 12,
    name: "CUTWORK POPLIN DRESS",
    price: 9950.0,
    image: image13,
    sizes: ["XS", "S", "M", "L"],
    colors: ["#DAA520", "#000000"],
    rating: 5,
    reviews: 95,
  },
  {
    id: 13,
    name: "CUTWORK POPLIN DRESS",
    price: 9950.0,
    image: image14,
    sizes: ["XS", "S", "M", "L"],
    colors: ["#2F4F4F", "#000000"],
    rating: 4,
    reviews: 83,
  },
  {
    id: 14,
    name: "CUTWORK POPLIN DRESS",
    price: 9950.0,
    image: image15,
    sizes: ["XS", "S", "M", "L"],
    colors: ["#800000", "#000000"],
    rating: 5,
    reviews: 110,
  },
  {
    id: 15,
    name: "CUTWORK POPLIN DRESS",
    price: 9950.0,
    image: image15,
    sizes: ["XS", "S", "M", "L"],
    colors: ["#8B008B", "#000000"],
    rating: 4,
    reviews: 79,
  },
  {
    id: 16,
    name: "CUTWORK POPLIN DRESS",
    price: 9950.0,
    image: image1,
    sizes: ["XS", "S", "M", "L"],
    colors: ["#F3E5D7", "#000000"],
    rating: 4,
    reviews: 87,
  },
  {
    id: 17,
    name: "CUTWORK POPLIN DRESS",
    price: 9950.0,
    image: image2,
    sizes: ["XS", "S", "M", "L"],
    colors: ["#FFB6C1", "#0000FF"],
    rating: 4,
    reviews: 87,
  },
  {
    id: 18,
    name: "CUTWORK POPLIN DRESS",
    price: 9950.0,
    sizes: ["XS", "S", "M", "L"],
    image: image3,
    colors: ["#000000", "#808080"],
    rating: 4,
    reviews: 87,
  },
  {
    id: 19,
    name: "CUTWORK POPLIN DRESS",
    price: 9950.0,
    sizes: ["XS", "S", "M", "L"],
    image: image4,
    colors: ["#D2B48C", "#000000"],
    rating: 4,
    reviews: 87,
  },
];

